name: Build Windows (PyAppify)

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Build with PyAppify
        id: build-app
        uses: ok-oldking/pyappify-action@master
        with:
          version: "v1.0.42"

      - name: Upload PyAppify artifact
        uses: actions/upload-artifact@v5
        with:
          name: StarResonanceMidi-pyappify
          retention-days: 14
          path: pyappify_dist/*
